name: emails_validator
description: Simple and efficient email address validator for Dart. Validates email syntax without using regular expressions, following RFC standards with detailed debug information.
version: 1.0.0

# Tags for pub.dev
topics:
  - email
  - validation
  - rfc
  - dart
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

dependencies: